# Generated by Django 4.0.6 on 2023-01-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_avatar_remove_customuser_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default='2000-01-02'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dofa',
            field=models.DateField(default='2000-01-02'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ippis_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
