# Generated by Django 4.0.6 on 2022-07-10 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_masterloandeductionsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterloandeductionsummary',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterloansummary', to=settings.AUTH_USER_MODEL),
        ),
    ]
