# Generated by Django 4.0.6 on 2022-07-10 09:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_masterloandeductionsummary_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterLoanDeductionSummary',
            new_name='MonthlyLoanDeductionSummary',
        ),
    ]
