# Generated by Django 4.0.6 on 2022-07-10 12:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_rename_masterloandeductionsummary_monthlyloandeductionsummary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterLoanDeduction',
            new_name='MonthlyLoanDeduction',
        ),
    ]
