# Generated by Django 4.0.6 on 2022-07-10 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_rename_masterloandeduction_monthlyloandeduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyloandeduction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='monthlyloandeduction', to=settings.AUTH_USER_MODEL),
        ),
    ]
