# Generated by Django 4.0.6 on 2022-07-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_monthlyloandeduction_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyloandeductionsummary',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='monthlyloandeductionsummary',
            name='narration',
        ),
    ]
