# Generated by Django 4.0.6 on 2022-07-11 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_masterloandeduction_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loans', to='core.product'),
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('narration', models.CharField(max_length=250)),
                ('transaction_code', models.BigIntegerField()),
                ('transaction_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loandeduction', to='core.loan')),
                ('loandeduction_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deductionuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
