# Generated by Django 4.0.6 on 2022-07-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_loan_product_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='core.loan'),
        ),
    ]
