# Generated by Django 4.0.6 on 2022-07-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deduction',
            old_name='loandeduction_user',
            new_name='loanee',
        ),
    ]
