# Generated by Django 4.0.6 on 2022-07-20 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_rename_loandeduction_user_deduction_loanee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loanbalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('transaction_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanbalances', to='core.loan')),
                ('loanee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='balancesuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
