# Generated by Django 4.0.6 on 2022-07-31 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_saving_savingmaster_delete_loanbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterSavingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('transaction_code', models.BigIntegerField()),
                ('monthly_cumulative', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mastersavingsummary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
