# Generated by Django 4.0.6 on 2022-07-31 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_masterloandeductionsummary_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterloandeductionsummary',
            name='transaction_date',
        ),
    ]
