# Generated by Django 4.0.6 on 2022-07-31 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_alter_saving_credit_alter_saving_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='savingcreatedby', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
