# Generated by Django 4.0.6 on 2022-10-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_saving_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deduction',
            options={'ordering': ['-transaction_date']},
        ),
        migrations.AddField(
            model_name='masterloandeduction',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
