# Generated by Django 4.0.6 on 2022-10-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_saving_credit_alter_saving_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='credit',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20),
        ),
        migrations.AlterField(
            model_name='saving',
            name='debit',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20),
        ),
    ]
