# Generated by Django 4.0.6 on 2022-10-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_saving_credit_alter_saving_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
