# Generated by Django 4.0.6 on 2022-10-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_saving_credit_alter_saving_debit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saving',
            options={'ordering': ['-transaction_date']},
        ),
    ]
