# Generated by Django 4.0.6 on 2022-11-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
