# Generated by Django 4.0.6 on 2023-01-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_profile_employment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ippis',
            new_name='staff_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='employment_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='dept',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
