# Generated by Django 4.0.6 on 2023-03-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_loan_guarantor_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursement_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
