# Generated by Django 4.0.6 on 2023-03-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_loan_disbursement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='transaction_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
