# Generated by Django 4.0.6 on 2023-03-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_loan_transaction_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='disbursement_date',
        ),
    ]
