# Generated by Django 4.0.6 on 2023-03-02 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0039_remove_loan_disbursement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='guarantor_one',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanguarantorone', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor_two',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanguarantortwo', to=settings.AUTH_USER_MODEL),
        ),
    ]
