# Generated by Django 4.0.6 on 2023-03-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_loan_guarantor_one_alter_loan_guarantor_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterloandeduction',
            name='balance',
        ),
    ]
