# Generated by Django 4.0.6 on 2023-04-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_product_created_product_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='guarantor_one',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='guarantor_two',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
