# Generated by Django 4.0.6 on 2023-04-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_loan_guarantor_one_alter_loan_guarantor_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='sub_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
