# Generated by Django 4.0.6 on 2023-04-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_loan_applied_amount_alter_loan_approved_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='deduction_sub_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
