# Generated by Django 4.0.6 on 2023-04-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
