# Generated by Django 4.0.6 on 2023-04-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_profile_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
