# Generated by Django 4.0.6 on 2023-05-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_profile_bank_alter_profile_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deduction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='saving',
            options={'ordering': ['transaction_date']},
        ),
    ]
