# Generated by Django 4.0.6 on 2023-05-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_deduction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saving',
            options={'ordering': ['-transaction_date']},
        ),
    ]
